name: Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  changelog:
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/changelog-reusable.yml
    with:
      app-client-id: ${{ vars.CHANGELOG_APP_CLIENT_ID }}
    secrets:
      app-private-key: ${{ secrets.CHANGELOG_APP_PRIVATE_KEY }}
